### ISSUE TITLE
Better Integration with camel

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#121]
**As** a user of the extension ` io.quarkiverse:quarkus-artemis-jms` who also uses camel

**when** I define `ConnectionFactory`s via a configuration file (`application.properties`/`application.yml`)

**then** I want that that those `ConnectionFactory`s are automatically registered in the camel context, so that I can use them via their name, e.g.:
```
from(jms("queue:in").connectionFactory("<default>"))
    .to(jms("queue:out").connectionFactory("named"));
```

---

**As** a user of the extension ` io.quarkiverse:quarkus-artemis-jms` who also uses camel

**when** I define `ConnectionFactory`s as beans in my application that have an [`@io.smallrye.common.annotation.Identifier("...")`](https://github.com/smallrye/smallrye-common/blob/main/annotation/src/main/java/io/smallrye/common/annotation/Identifier.java)

**then** I want that that those `ConnectionFactory`s are automatically registered in the camel context, so that I can use them via their name, e.g.:
```
from(jms("queue:in").connectionFactory("named"))
    .to(jms("queue:out").connectionFactory("externally-defined"));
```

---

**As** a user of the extension ` io.quarkiverse:quarkus-artemis-jms` who also uses camel

**when** I use only one `ConnectionFactory` (either through configuration or externally defined)

**then** I want that this connection factory is registered automatically, and I do not have to set it explicitly, e.g.:
```
from(jms("queue:in"))
    .to(jms("queue:out"));
```

**Comment by zhfeng** [comment]
Thanks @turing85 and I think the case 1 and case 3 should be supported in `camel-quarkus-jms` already. It could register all the beans from `quarku-arc` container automatically. In case 2, if  `@Identifier` is recognized as bean, it should be good too. So I wonder if all the integration tests with camel-quarkus-jms could be moved to [camel-quarkus/integration-tests/jms-artemis-client](https://github.com/apache/camel-quarkus/blob/main/integration-tests/jms-artemis-client) to see if they pass.

**Comment by turing85** [comment]
For more details on case 1 and 3, see [this](https://github.com/quarkiverse/quarkus-artemis/pull/122#discussion_r1045858434), [this](https://github.com/quarkiverse/quarkus-artemis/pull/122#discussion_r1046036260) and [this](https://github.com/quarkiverse/quarkus-artemis/pull/122#discussion_r1046296190) comment. 

Short summary: as of now, all parts implemented in this enhancement are needed; none of them are automated by camel.

**Comment by zhfeng** [comment]
Hi @turing85 

I think this could be similar with https://github.com/apache/camel-quarkus/issues/4063. We add the `@Identifier` Qualifier, and it makes looking for  `ConnectionFactory` bean failing.  So I think we have to register a `CamelBeanQualifierResolverBuildItem` such like https://github.com/apache/camel-quarkus/blob/main/extensions-support/jdbc/deployment/src/main/java/org/apache/camel/quarkus/support/jdbc/deployment/JdbcSupportProcessor.java#L37

I will figure it out.

**Comment by zhfeng** [comment]
Well, the root cause is that we was missing `configurator.name(name);` in `ArtemisJmsProcessor.java`. After adding it, all the camel-jms tests should work.

**Comment by zhfeng** [comment]
@turing85 Please check https://github.com/quarkiverse/quarkus-artemis/pull/125

**Comment by zhfeng** [comment]
And for case 2 it also need `@Named("externally-defined")` to make the ConnectionFactory to be looked up for camel-quarkus registry.
