### ISSUE TITLE
Integrate camel enhancements in quarkus-artemis 3

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#154]
We added some additional camel support in #121. Due to the fact that quarkus 3 makes the switch from JavaEE to JakartaEE, and camel 4 makes the switch from JavaEE to JakartaEE, we need to wait to port this changes into quarkus-artemis 3 until camel-quarkus 3, based on camel 4, is released.

**Comment by turing85** [comment]
`quarkus-camel` is available in quarkus version `3.0.0.Beta1`. Thus, the ticket is unblocked

**Comment by louisa-fr** [comment]
I would like to work on this :)

**Comment by louisa-fr** [comment]
Blocked by: https://github.com/apache/camel-quarkus/issues/4725 , but there is already a PR in progress to solve it
