### ISSUE TITLE
Remove code to register @Identifier beans in camel context

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#155]
We added some code to explicitly register beans with the `@Identifier` bean specifier to the camel context [here](https://github.com/quarkiverse/quarkus-artemis/blob/HEAD/jms/deployment/src/main/java/io/quarkus/artemis/jms/deployment/camel/CamelJmsRegistryEnhancerProcessor.java) and [here](https://github.com/quarkiverse/quarkus-artemis/blob/HEAD/jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/camel/CamelContextEnhancer.java). PR https://github.com/apache/camel-quarkus/issues/4374 adds general support for `@Identifier` beans in quarkus-camel. The release is scheduled for camel-quarkus 3. 

We should remove this code when camel-quarkus 3 is released. The optional dependency to `camel-quarkus` should also be removed from [here](https://github.com/quarkiverse/quarkus-artemis/blob/main/jms/deployment/pom.xml#L43), and [here](https://github.com/quarkiverse/quarkus-artemis/blob/main/jms/runtime/pom.xml#L53); the bom-import should be moved from [here](https://github.com/quarkiverse/quarkus-artemis/blob/main/build-parent/pom.xml#L31) to [here](https://github.com/quarkiverse/quarkus-artemis/blob/main/integration-tests/camel-jms/pom.xml#L23).

This issue must be resolved after or in conjunction with #154 .

**Comment by turing85** [comment]
I did some prelimiary testing with `camel-quarkus-jms:3.0.0-M1` (where the PR mentioned above is included). Right now, camel seems to operate under the constraint that bean-names are unique. This works perfectly fine for bean we create within the extension. It does, however, not work for externally defined beans, since we may have two beans with the same name (e.g. an `ArtemisJmsConsumerManager` and a `ActiveMQConnectionFactory`, see https://github.com/quarkiverse/quarkus-artemis/blob/2.x/integration-tests/camel-jms/with-named-and-external/src/main/java/io/quarkus/it/artemis/camel/jms/withnamedandexternal/BeanProducer.java for an example).

There is a simple workaround (which can be implemented on our side) and a possible proper fix (which most be implemented in camel, most likely in the core):
- Workaround: give dedicated names for connection factories and consumers/producers, e.g. `"externally-defined"` for the connection factory and `"externally-defined-consumer"` for the consumer).
- Fix: see [this zulip discussion](https://camel.zulipchat.com/#narrow/stream/257302-camel-quarkus/topic/Resolution.20of.20.40Identifier.20dependency).

**Comment by middagj** [comment]
Interesting, so basically problem is that Camel tries to wire Object beans? If we add the workaround, aren't we committing ourselves to that and make it even harder to revert? How is the `@Identifier` being done in Camel? Can we just issue a warning in the documentation if people are hit by it? Would that be advanced use cases, or is it quite normal? Asking these questions because I don't like the workaround 😄

**Comment by turing85** [comment]
[Here](https://github.com/apache/camel-quarkus/commit/6f4228848ef68eff290ef735d8552dcc23cf7266#diff) are the changes of the corresponding PR to support `@Identifier`.

For the time being, I think the best course of action from our side is to not remove the registration code.

**Comment by zhfeng** [comment]
I agree and it would take more efforts to fix in camel.

**Comment by turing85** [comment]
I raised https://github.com/apache/camel-quarkus/issues/4725 to tackle the issue in camel.

**Comment by louisa-fr** [comment]
Already worked on this together with #154 , the results are also in branch https://github.com/quarkiverse/quarkus-artemis/tree/%23154%2B%23155, still blocked by the issue @turing85 mentioned above but there is already a PR in camel to solve it: https://github.com/apache/camel/pull/9811
