### ISSUE TITLE
pipeline: remove package-phase from populate-cache job

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#156]
We added the `package`-phase, as well as some configuration (`--define skipTests` and `--define no-format`) [here](https://github.com/quarkiverse/quarkus-artemis/blob/main/.github/workflows/build.yml#L102) to work around a bug in the target `go-offline` of the `quarkus-maven-plugin`. PR https://github.com/quarkusio/quarkus/pull/31092 resolves the bug and is scheduled for realease in version 3.0.

When quarkus 3 is released, we should revert those changes and remove the TODO.

**Comment by turing85** [comment]
The merge request in quarkus is released with `3.0.0.Alpha5`. Thus, this issue is ready for development

**Comment by louisa-fr** [comment]
I would like to work on this, too :) (Marco knows about it)
