### ISSUE TITLE
Remove io.quarkus:quarkus-jms-spi-deployment in build-parent

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-artemis#167]
When upstream quarkus 3.0.0 have a new release which include fix of 
- https://github.com/quarkusio/quarkus/pull/31074

We should remove `io.quarkus:quarkus-jms-spi-deployment` in build-parent and this has been done in 
- https://github.com/quarkiverse/quarkus-artemis/pull/166 for `2.x` branch

**Comment by turing85** [comment]
@all-contributors add @zhfeng as code and maintenance

**Comment by turing85** [comment]
The merge request in quarkus is released with `3.0.0.Alpha5`. Thus, this issue is ready for development
