### ISSUE TITLE
Replace constructor calls of ReflectiveCallBuildItem with builder calls

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#184]
The constructor [`ReflectiveClassBuildItem(boolean, boolean, String...)`][reflectiveSource] has been deprecated. We are calling the constructor in `ArtemisCoreProcessor` [here][usageOne] and [here][usageTwo]. We need to replace those constructor invocations with invocations of [the new builder of `ReflectiveClassBuildItem`][reflectiveBuilderSource].

[reflectiveSource]: https://github.com/quarkusio/quarkus/blob/HEAD/core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java#L85

[usageOne]: https://github.com/quarkiverse/quarkus-artemis/blob/HEAD/core/deployment/src/main/java/io/quarkus/artemis/core/deployment/ArtemisCoreProcessor.java#L132

[usageTwo]: https://github.com/quarkiverse/quarkus-artemis/blob/HEAD/core/deployment/src/main/java/io/quarkus/artemis/core/deployment/ArtemisCoreProcessor.java#L140

[reflectiveBuilderSource]: https://github.com/quarkusio/quarkus/blob/HEAD/core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java#L37

**Comment by turing85** [comment]
Please do not implement this feature, I have someone in mind to do the implementation.

**Comment by louisa-fr** [comment]
I would like to work on this :) (Marco knows about it)
