### ISSUE TITLE
Support for multiple named connection factories

### ISSUE THREAD

**Issue by NickPaul41** [quarkiverse/quarkus-artemis#20]
Feature request similar to https://github.com/amqphub/quarkus-qpid-jms/issues/13

Support for multiple named connection factories similar to Quarkus datasources

    https://quarkus.io/guides/datasource#multiple-datasources

**Comment by middagj** [comment]
Sounds like a good idea. Feel free to implement it. I don't know when I have time to work on it.

**Comment by turing85** [comment]
Do we have an idea how to handle this with devservices?

**Comment by turing85** [comment]
I have [started working on this feature](https://github.com/turing85/quarkus-artemis/tree/feature/20-add-named-connections). I think it is mostly done. Missing:
- tests
- devmode setup for named connections

A review on the work so far is welcome.

**Comment by middagj** [comment]
Great, could you put in a MR. Makes review easier. One thing I noticed is that you using lambdas. This is not done in Quarkus code anymore due to performance reasons. Could you change `Optional.of().map().orElse` to normal flow and keep the anonymous classes?

**Comment by turing85** [comment]
PR is open. There's still a problem with "detecting" all configured, named connections at compile-time though. And the handling of devservices is still TBD.
