### ISSUE TITLE
Artemis ConnectionFactory registered under ApplicationScope, does not register XAResourceRecovery on application start

### ISSUE THREAD

**Issue by tmielke** [quarkiverse/quarkus-artemis#230]
The Artemis ConnectionFactory [gets registered ](https://github.com/quarkiverse/quarkus-artemis/blob/main/jms/deployment/src/main/java/io/quarkus/artemis/jms/deployment/ArtemisJmsProcessor.java#L104) as ApplicationScoped [1], which means its lazily instantiated when a method is invoked.
As a result it does not register an `XAResourceRecovery` at application startup. This makes it impossible to recover pending XA transactions when restarting after a crash.

**Comment by tmielke** [comment]
With the help of @zhfeng we found a workaround which is to call `ConnectionFactory.getConnection()` in a `@PostConstruct` method of a bean that is created at application startup time (and not lazily on demand).

**Comment by turing85** [comment]
Hm... interesting... 

@middagj, @zhfeng do you know whether thereis a way to enforce bean creation through the extension?

**Comment by zhfeng** [comment]
@turing85 as far as I know, it could set scope to `Singleton`. Something like quarkus agroal https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java#L275-L280

**Comment by middagj** [comment]
Yes, `@Singleton` is created on injection. An alternative is observing StartupEvent: https://quarkus.io/guides/cdi-reference#startup_event

**Comment by turing85** [comment]
> @turing85 as far as I know, it could set scope to `Singleton`. Something like quarkus agroal https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java#L275-L280

@zhfeng do you know whether `@Singleton`s are registered in the camel context?

**Comment by turing85** [comment]
Okay, let me do a quick test. This should be easy to verify.

**Comment by turing85** [comment]
@zhfeng I have already backported it locally. As soon as the PR is merged, I'll push the backport

**Comment by turing85** [comment]
Fix has been released with versions [`3.0.1`](https://github.com/quarkiverse/quarkus-artemis/releases/tag/3.0.1) and [`2.1.1`](https://github.com/quarkiverse/quarkus-artemis/releases/tag/2.1.1).

**Comment by zhfeng** [comment]
Thanks a lot!
