### ISSUE TITLE
quarkus `3.3`, branching for `3.2` LTS and the change from `nativeimage:svm` to `sdk:graal-sdk`

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#248]
The next minor release of quarkus (`3.3`) brings some changes that must be handled in conjunction.

1. quarkus `3.2` as LTS
   For LTS support, we need a separate branch. I propose to use a `3.0`  branch, which "tracks" quarkus `3.2`, making our `3.0` compatible with quarkus `3.2` LTS. We need to set-up corresponding dependabot-rules.
2. With quarkus `3.3`, https://github.com/quarkusio/quarkus/pull/34145 is planned to come into effect. The change on our end was already done in #246, but is - as of now - unreleased. When quarkus `3.3` lands (and we upgraded), we need to produce a new release. I propose version `3.1.0`, so it does not interfer with the `3.0`-branch for LTS support of quarkus `3.2`.
3. As of now, it is unclear whether the change to `nativeimage:svm` will be downstreamed to `3.2`. Hence we need to look out for this change hitting `3.2`. The relevant commit-id in quarkus is `70e837b427d4f4be6c6946e559561f6236d6d834`.
4. We should provide a compatibility list that shows which of our releases correlate to (LTS)-releases of quarkus. As of now:
   - Our `2.x` is compatible with quarkus `2.x` (I have no exact data on this, I know it is compatible with at least `2.13.x`)
    - Our `3.0`  is compatible with all quarkus `3.0`-, `3.1`- and `3.2`-releases
    - Our  latest`3.0` will support quarkus `3.2` LTS
    - Our latest `3.1` will support quarkus `3.3` and onwards

**Comment by middagj** [comment]
Small comment, does a 3.1 increment leaves enough room for a possible non-patch release on 3.2 LTS? Or that is just not expected as also Quarkus does not leave room for it.

**Comment by turing85** [comment]
Well, everything in `3.0` must be on minor level semantics, i.e. only non-breaking changes. If we want the possibility for breaking changes, we'd need a `3.2` brach and "leava a gap" (which is most probably confusing to most people)

**Comment by middagj** [comment]
True, let's do 3.1. Purpose of LTS is to be stable, so means patch only.

**Comment by turing85** [comment]
Branch `3.0.x` is created.
The documentation update for the compatibility list has been merged (#250) and downstreamed to branches `3.0.x` and `2.x`.
A PR for the corresponding dependabot-config has been created (#261). When this PR is merged, it will be downstreamed to branches `3.0.x` and `2.x`.
A Release PR for version 3.1.0 has also been created (#262).
