### ISSUE TITLE
Artemis native build is failing with java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-artemis#347]
It seems that we remove the following in `core/runtime/pom.xml`
```
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>commons-logging-jboss-logging</artifactId>
</dependency>
```
 in https://github.com/quarkiverse/quarkus-artemis/commit/d3b2cf0345d30eae4d2a1fc7bf4d42dcf881a12d#diff-40752b74da493b2aa06facf4b1ebd7a81736f6318dcfe76ddae90deafa57fad7

We have to add this artifact because it is needed by `artemis-core-client`.

The CI is working because `commons-logging-jboss-logging` is comming from `io.quarkus:quarkus-junit5`. We set it as `compile` scope in `integration-tests/core/common/pom.xml` and I think it coud be wrong.

**Comment by turing85** [comment]
> What I understood when working on this, was that we have to exclude all logging and it will be included via Quarkus.

I do not fully understand this comment. As far as I can see, it is not added, and it is needed by `artemis-core`, i.e. a dependency we pull in. As such, we should provide it in our runtime. Maybe we should add a corresponding comment, pointing out that we need this dependency for `artemis-core`. We probably also need to add it in the runtime of `artemis-jms` then. And we can then remove the explicit import in `integration-tests/common-parent`.

**Comment by gastaldi** [comment]
> @gastaldi any idea? `commons-logging-jboss-logging` is included in Quarkus? Or we have to add it here?

`org.jboss.logging:commons-logging-jboss-logging` is a managed dependency in the Quarkus BOM. It should be added here if your extension needs it.

**Comment by middagj** [comment]
It was too early this morning, I thought this was about the exclusions. But yes Quarkus uses JBoss and we want to exclude all the other logging frameworks indeed.
