### ISSUE TITLE
Make quarkus.artemis.url optional

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-artemis#36]
I just moved https://github.com/quarkusio/quarkus/issues/18231 here to track it.

**Comment by turing85** [comment]
@zhfeng What is the current status on how this should behave? Based on the implementation I am doing in #20, I can quite easily:
- return `null`s when the URL is not set at runtime
- exclude everything with `null`  URL from the health check(s).

This could ultimately lead to a situation where the health endpoint has no items, i.e. always returns `"UP"`.

Are those specifications acceptable?
