### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by timonzi** [quarkiverse/quarkus-artemis#365]
I only want to give the hint, that the link to the documentation is broken, respectively the `dev` and `3.0.x` sites are not available.

So for
* https://docs.quarkiverse.io/quarkus-artemis/dev/index.html
* https://docs.quarkiverse.io/quarkus-artemis/3.0.x/index.html
I get a "Page Not Found" message.

https://docs.quarkiverse.io/quarkus-artemis/2.x/index.html works fine.

**Comment by zhfeng** [comment]
Thanks @timonzi for reporting and I think it due to the following PR which I removed `index.adoc`
- #361
