### ISSUE TITLE
Additional ActivationSpec properties for the resource adapter

### ISSUE THREAD

**Issue by gtudan** [quarkiverse/quarkus-artemis#400]
We have an existing application that we would like to port to quarkus. Since we don't want to change to much in the first iteration, using the resource adapter seems to be the simplest way to do it. 

There are a couple of activation spec properties that are not in the ResourceAdapterFactory (yet?):

* messageSelector
* subscriptionDurability
* subscriptionName
* shareSubscriptions

Would you accept a PR if we add them?

**Comment by gtudan** [comment]
I'm unsure if I should add the properties to the documentation here: https://docs.quarkiverse.io/quarkus-artemis/dev/quarkus-artemis-ra.html#_in_your_application

Adding all of the optional properties could make this confusing.

**Comment by middagj** [comment]
@zhfeng I assigned you to this one, as (if I remember correctly) you are the one initially working on it.

**Comment by turing85** [comment]
Hmm... wrt. the documentation: we basically proxy the configurations for [`ActiveMQResourceAdapter`](https://github.com/apache/activemq-artemis/blob/main/artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQResourceAdapter.java). I do not think that we should list everything that is settable, but  link to a resource that documents what is settable. Wouldn't [this readme at `activemq.apache.org`](https://activemq.apache.org/components/artemis/documentation/latest/resource-adapter.html#activationspec) the source of truth?

**Comment by turing85** [comment]
@gtudan I would ask you for  some patience. We would like to have the opinion of @zhfeng since he implemented the feature and is the one most familiar with resource adapters on our small team :slightly_smiling_face: . Unfortunately, he is currently unavailable. I think he should be available at around the 19th of February.

**Comment by gtudan** [comment]
@zhfeng Don't want to be pushy, but could you please take a look at that PR of mine?

**Comment by zhfeng** [comment]
@gtudan I'm very sorry for the late reply and yeah, I will take a look.

**Comment by turing85** [comment]
@louisa-fr, @middagj, @zhfeng what do you think? Should we release a new version with this feature?

**Comment by gtudan** [comment]
> @gtudan I'm very sorry for the late reply and yeah, I will take a look.

Awesome, thanks a lot!

**Comment by middagj** [comment]
> @louisa-fr, @middagj, @zhfeng what do you think? Should we release a new version with this feature?

Before we release can @gtudan confirm that this is working (or we can release a CR if that is easier)

**Comment by gtudan** [comment]
I'll give it a try and let you know

**Comment by gtudan** [comment]
Hi, I was able to validate most of the added properties
✅ share-subscriptions
✅ subscription-durability (careful, it's case sensitive)
✅ message-selector
❔subscription-name - I see that it is passed correctly in the debugger, but I'm not sure if is shown in the Artemis console somewhere

**Comment by zhfeng** [comment]
@gtudan `3.2.1` is out!

**Comment by turing85** [comment]
All changes are also downstreamed to `3.0.x` and `3.1.x`. We plan to release those changes shortly as well (probably early next week).
