### ISSUE TITLE
Discontinue quarkus-artemis 2.x

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#426]
Quarkus 2.13 reaches its EOL on 2024-04-30 (see [here (`access.redhat.com`)](https://access.redhat.com/support/policy/updates/jboss_notes#p_quarkus)).

On this day, we should:
- [x] produce one final release of `quarkus-artemis 2.x` (probably version `2.1.4`)
- [x] add an additional tag (`2.x-discontinued`) over on the same commit of the final relese
- [x] remove the branch `2.x` from [`quarkivese-doc`'s `antora-playbook.ym`](https://github.com/quarkiverse/quarkiverse-docs/blob/main/antora-playbook.yml#L27), add the last release tag
- [x] remove the [`backport/2.x` label](https://github.com/quarkiverse/quarkus-artemis/labels/backport%2F2.x)
- [x] remove the `2.x`-branch
- [x] (a day or so later) Verify that the branch `2.x` has been replaced by the tag on https://docs.quarkiverse.io/quarkus-artemis/dev/index.html 

Questions:
- Should we also delete the branch? We would still have the tags, so the code should still be present. It is possible to point the [`antora-playbook.yml` (`github.com`)](https://github.com/quarkiverse/quarkiverse-docs/blob/main/antora-playbook.yml) against a tag (see [here (`docs.antora.org`)](https://docs.antora.org/antora/latest/playbook/content-tags/#tags-key)). In this case, we would need to open a PR against https://github.com/quarkiverse/quarkiverse-docs. @gastaldi do you know whether referencing tags may cause issue with the current setup? It seems that nobody uses tags as of now. -> Yes, we want to delete the branch

@middagj, @zhfeng what do you think about deleting the branch?

**Comment by gastaldi** [comment]
@turing85 I don't think referencing tags is a problem if Antora supports it

**Comment by middagj** [comment]
If we are not going to continue I would delete the branch. We have tags so we don't lose the commits on cleaning.
