### ISSUE TITLE
Discontinue quarkus-artemis 3.1.x

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#503]
Quarkus `3.3.x` to `3.7` has reached its end of life [a while back (`endoflife.date`)](https://endoflife.date/quarkus-framework). Instead of removing it immediately, I propose a grace period of maybe 2 months to then take our branch (`3.1`) end of life as well (i.e. on `2024.06-30`).

On this day, we should:
- [x] produce one final release of `quarkus-artemis 3.1.x` (probably version `3.1.6`)
- [x] add an additional tag (`3.1.x-discontinued`) over on the same commit of the final relese
- [x] remove the branch `3.1.x` from [`quarkivese-doc`'s `antora-playbook.ym`](https://github.com/quarkiverse/quarkiverse-docs/blob/main/antora-playbook.yml#L27), add the last release tag
- [x] remove the [`backport/3.1.x` label](https://github.com/quarkiverse/quarkus-artemis/labels/backport%2F3.1.x)
- [x] remove the `3.1.x`-branch
- [x] (a day or so later) Verify that the branch `3.1.x` has been replaced by the tag on https://docs.quarkiverse.io/quarkus-artemis/dev/index.html 

@middagj, @zhfeng, @louisa-fr what do you think? Are two months enough?

**Comment by middagj** [comment]
Same as previous time or not? I would change `discuntionued` into the proper one.

Two months is good for me.

**Comment by turing85** [comment]
> Same as previous time or not? I would change `discuntionued` into the proper one.
> 
> Two months is good for me.

Embarrassing. Done.
