### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by timonzi** [quarkiverse/quarkus-artemis#76]
Hello,

I would like to know whether there is a release plan for the Quarkus Artemis extension.
We possibly will need an updated Artemis version soon, because of the following issue:
https://issues.apache.org/jira/browse/ARTEMIS-3843

I would be interesting to know when a new release can be expected.

**Comment by gsmet** [comment]
I started the release here: https://github.com/quarkiverse/quarkus-artemis/pull/77

New release will be available today.

**Comment by gsmet** [comment]
`1.3.0` is available on Maven Central.

**Comment by timonzi** [comment]
Thank you very much!
