### ISSUE TITLE
Health check: check ServerLocator- and ConnectionFactory-beans created outside the extension

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#84]
This is a follow-up of #36.

As of now, `ServerLocator`- and `ConnectionFactory`-beans created outside the extension. In general. however, this should be possible by:
- getting all beans implementing `ServerLocator`- or `ConnectionFactory`-beans,
- filtering-out the ones already handled by the extension, and
- add the beans to the health check.
We will attribute those beans created outside the extension as *external bean* for the following disucssion.

Challenges:
1. We need to generate sensible names for the external beans. We cannot reliably detect scope-annotations since there is a multitude of annotations that could be used, including user-defined scopes.
2. There might be an issuse with "duplicate" beans. IIRC, the [quarkus-pooled-jms extension](https://github.com/quarkiverse/quarkus-pooled-jms) wraps already-existing connection factories into a wrapper-factory for pooling. Thus, we have - on a technical level - two `ConnectionFactory`-beans representing the same connection.

**Comment by middagj** [comment]
What if we would ask our users to add an annotation to beans created outside the extension they want to have included in the service health check. They can provide a name in the annotation. I think it is very difficult to determine in the extension what the purpose is of the beans with said type. The application can make this judgement far better.

**Comment by turing85** [comment]
I'd vote for `@Identifier` in this case.

**Comment by turing85** [comment]
@zhfeng I took another look at the pooled-jms extension. I think the concern I had wrt. connection factories created twice is not correct. Can you confirm?

**Comment by turing85** [comment]
@middagj  @zhfeng So if my assumption wrt. quarkus-pooled-jms is correct and we decide to use `@Identifier(...)` as annotation to use for externally configured beans, I have an implementation ready. Just say the word, and I will open a MR.

**Comment by middagj** [comment]
> The more I think about this, the more I have a problem with this approach. Readiness-probes control whether the pod should be taken out of the load balancer. With the current approach, we enforce on the user that each server locator / connection factory is automatically added to the readiness check.

Using the health check for a readiness probe is a decision beyond our control. Usually a readiness check needs 3 failing checks. Apart from that, health check only indicate if a new connection can be created, (or a pooled connection still work), it doesn't say if current connections work.

But I agree, there should be an option to disable beans from a health check. Is something similar already implemented for DataSources?

**Comment by turing85** [comment]
Careful: we add readiness-checks, not health-checks (afaik, all quarkus extensions register readiness-checks). The number of failing readiness-checks is also configurable before the service is regarded as "not ready". But assuming thath `/q/health/ready` is registered as a k8s/OpenShift readiness check is quite sensible, and we should plan for this.

**Comment by middagj** [comment]
Yes, we should definitely think about the use case and plan, but at least for k8s, you still need to register the check yourself.

**Comment by turing85** [comment]
Given that most people will streamline the generation of services, I recon that `/q/health/ready` is registered in some base (at least this is what one of my cusotmer does). I have introduced a runtime-variable that controls whether such a check should be included or not, defaulting to `true`. Thus, users have the possibility to turn it off.
