### ISSUE TITLE
Prepare for Quarkus 3.0.0

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-artemis#87]
In the advent of the Quarkus 3.0.0 release, we should prepare this extension.

**Comment by turing85** [comment]
I did a preliminary test and for us, it seems that migration boils down to replacing some imports:
- `javax.enterprise` -> `jakarta.enterprise`
- `javax.ws` -> `jakarta.ws`
- `javax.transaction` -> `jakarta.transaction`

**Comment by middagj** [comment]
Great, let's wait for the first alpha and create a branch.

**Comment by zhfeng** [comment]
@middagj I find that you bump the version to `2.0.0` in the lastest release. So what is our stragtegy for the coming Quarkus 3? keep the `main` branch to align to Quarkus 3 and make `2.x` branch for keeping support Quarkus 2.x?

**Comment by middagj** [comment]
Yes, that would be my proposal. Perhaps we can back port some features to the 2.x branch as well, but we won't do any major features.

The bump to 2.0.0 was to signal the changes in config.

**Comment by turing85** [comment]
@middagj I plan to make an alpha release so that other extensions, depending on us, can test compatibility. Thought of releasing as `3.0.0.Alpha1`. What do you think?

**Comment by middagj** [comment]
If you have the time it would be an excellent idea. Can you make the release on a separate branch and merge it once we get out of alpha?

**Comment by turing85** [comment]
I have a hunch that we can make a merge on the current feature branch, changing the version and everything should run. Will try it in a moment.

**Comment by turing85** [comment]
Yup, just worked. Relese pipeline is running.

**Comment by turing85** [comment]
... [welp](https://github.com/quarkiverse/quarkus-artemis/actions/runs/3361978572/jobs/5573087126#step:9:1168)...

**Comment by turing85** [comment]
This was a trip and a half. We have a Release `3.0.0.Alpha1` and `3.0.0.Alpha2` now (2 releases b/c something with the pipeline went wrong, that's also the reason why there is no tag for `3.0.0.Alpha1`).

**Comment by turing85** [comment]
`quarkus-pooled-jms` cannot compile due to a version incompatibility of `jarkarta.jms-api` (we use `2.0.3`, `quarkus-pooled-jms` as well as `quarkus-jta` uses `3.0.0`).

I think we need a release of `artemis-[core|jms]-client` based on `jakarta.jms-api` version `3.0.0`. @middagj can you confirm this? As of now, I see no way we can somehow "bridge" between two jakarta versions.

See [this issue](https://github.com/quarkiverse/quarkus-pooled-jms/issues/39#issuecomment-1297809911) for details.

**Comment by zhfeng** [comment]
@turing85 Also it looks like we need to change to use `org.apache.activemq:artemis-jakarta-client`?

**Comment by turing85** [comment]
@zhfeng didn't knew they had a separate client. This is probably the solution to this problem.

**Comment by middagj** [comment]
Is there any convention in Quarkus with respect to the import order of `jakarta.*`?

**Comment by turing85** [comment]
Not that I know of.

**Comment by turing85** [comment]
As of now, we cannot merge the "meat" of #121 into this branch since camel has not yet upgraded to quarkus 3. I have merged the non-essential parts (i.e. the test restructuring and the pipeline upgrades), but the rest can only be merged after we have a camel release that works with quarkus 3.

**Comment by zhfeng** [comment]
@turing85 @middagj Quarkus 3 has been out last week. Then I wonder if we need to bump our `main` branch to support Quarkus 3 and create a new branch `quarkus-2.x` to maintain Quarkus 2.16.x. As far as I know, there is no plan to release 2.17 with Quarkus.

**Comment by turing85** [comment]
@zhfeng `2.17` is in deed not planned. I see, however, no `3.0.0` release in mvnrepository, nor a `3.0.0` tag in github. Are you sure a final version is out?

**Comment by zhfeng** [comment]
@turing85 
- https://github.com/quarkiverse/quarkus-artemis/issues/121 I think it is no need to merget it since 
- https://github.com/apache/camel-quarkus/issues/4374 has been resolved and it will be included in camel-quarkus (maybe 3.x) which we are working on.

**Comment by zhfeng** [comment]
Sorry @turing85 ,  I just see the Quarkus main branch has been transform to support Jarkata EE 10 completely. And yeah, we can still wait the Quarkus 3.0.0.Final release. I belive it could happen very soon.

**Comment by turing85** [comment]
@middagj, @zhfeng I'd like to push this branch to develop next week. My Idea:
- create a branch `2.x` from the current `develop` and push it:
  ```
  git fetch origin main:main
  git switch main
  git checkout -B 2.x
  git push origin 2.x:2.x
  git switch main
  ```
- Transfer the current state of `feature/87-prepare-for-quarkus-3` to `develop`. This is a mulit-step process:
  - Merge `develop` int `feature/87-prepare-for-quarkus-3` through a fast-forward commit that discards everything from `develop` and keeps `feature/87-prepare-for-quarkus-3`:
    ```
    git fetch origin main:main
    git fetch origin feature/87-prepare-for-quarkus-3:feature/87-prepare-for-quarkus-3
    git switch feature/87-prepare-for-quarkus-3
    git merge --ff-only $(git commit-tree -m "merge main into feature/87-prepare-for-quarkus-3, discard main" -p feature/87-prepare-for-quarkus-3 -p main feature/87-prepare-for-quarkus-3^{tree})
    ```
  - Compare the current head of `feature/87-prepare-for-quarkus-3` with commit https://github.com/quarkiverse/quarkus-artemis/commit/2e123cce2897a666fd96bcebbb9ad5965f452b3f. They should be identical.
  - Push the new commit onto `feature/87-prepare-for-quarkus-3`:
    ```
    git push
    ```
  - Ppen a PR from `feature/87-prepare-for-quarkus-3` to `main` and merge the PR.
- Update [`antora.yml`](https://github.com/quarkiverse/quarkus-artemis/blob/main/docs/antora.yml#L3) on new brauch `2.x`: set `version` to `2.x`
- Update [`quarkiverse/antorya-playbook.yml`](https://github.com/quarkiverse/quarkiverse-docs/blob/main/antora-playbook.yml#L82): set `branches` to `[HEAD, 2.x]` 

WDYT? Are you on board with this plan?

**Comment by zhfeng** [comment]
@turing85 It looks good to me! The only thing I can recall is about `dependabot.yml`. It could be possible to add a new `target-branch` for `2.x`, just like

```yaml
- package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "2.x"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"

```

**Comment by zhfeng** [comment]
And for `.github/workflows/build.yml`, it needs to add `2.x` branch for building on push:

```yaml
  push:
    branches:
      - "main"
      - "2.x"
```

**Comment by turing85** [comment]
> @turing85 It looks good to me! The only thing I can recall is about `dependabot.yml`. It could be possible to add a new `target-branch` for `2.x`, just like
> 
> ```yaml
> - package-ecosystem: "maven"
>     directory: "/"
>     schedule:
>       interval: "daily"
>     target-branch: "2.x"
>     ignore:
>       - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
> ```

Didn't want to do all in this issue. Dependabot is not totally trivial. We have to talk about dependencies and what versions we want in the `2.x` branch (for most dependencies, I think it is irrelevant, but at least for quarkus and camel, we need to limit the versions to `2.x`)

**Comment by turing85** [comment]
> And for `.github/workflows/build.yml`, it needs to add `2.x` branch for building on push:
> 
> ```yaml
>   push:
>     branches:
>       - "main"
>       - "2.x"
> ```

@zhfeng Added to the list above :+1:

**Comment by turing85** [comment]
@zhfeng I've raised #157 for the dependabot configuration.

**Comment by zhfeng** [comment]
Thanks @turing85 and it is awesome!

**Comment by turing85** [comment]
Please feel free to enhance/modify #157 as you see fit. I just wrote down what came to my mind, it might be that I've missed things.

**Comment by zhfeng** [comment]
Sure - Hmm, it looks like I have no write permission to edit issue since I'm not the committor of `quarkus-artemis`. So @middagj @turing85 May I ask to add me as a committor? :stuck_out_tongue:

**Comment by turing85** [comment]
Hmm.... I have no idea how :sweat: At least I have no permission to do it via the web UI. @middagj should know the process.

**Comment by zhfeng** [comment]
It seems that it needs to change https://github.com/quarkiverse/quarkiverse-devops/blob/main/quarkus-artemis.tf and raise a PR against `quarkiverse-devops`. I think @gastaldi maybe help here.

**Comment by turing85** [comment]
ping me if you've opened the PR, I'll gladly approve it

**Comment by gastaldi** [comment]
Here is the PR: https://github.com/quarkiverse/quarkiverse-devops/pull/120

**Comment by zhfeng** [comment]
Wooh, thanks everyone for helping! It works now. :smile:

**Comment by zhfeng** [comment]
@turing85 I also add a step to replace `999-SNAPSHOT` to `2.x-999-SNAPSHOT` for `2.x` branch.

**Comment by middagj** [comment]
Welcome aboard!

> WDYT? Are you on board with this plan?

I think the proposed approach (make 3.0 the main branch and branch off for 2.x) is good.

**Comment by turing85** [comment]
@middagj, @zhfeng I plan to start the switch today.

**Comment by zhfeng** [comment]
@turing85 Are you going to do a new Alpha release of 3.0.0 after switching?

**Comment by turing85** [comment]
@zhfeng I did not plan to, no.

**Comment by turing85** [comment]
Starting the process now.

**Comment by turing85** [comment]
Switch is done.

**Comment by turing85** [comment]
@middagj @zhfeng could you double-check if everything is in order?

Furthermore, @middagj can you protect branch `2.x`? Or do we need someone from "higher up"?

**Comment by middagj** [comment]
I could not find it easily, but you should have same rights. Will check tomorrow

**Comment by middagj** [comment]
Camel support was removed on purpose I recon. I didn't see anything strange, just Javadoc that got over 120 line width due to renaming.

**Comment by turing85** [comment]
> Camel support was removed on purpose I recon. I didn't see anything strange, just Javadoc that got over 120 line width due to renaming.

Yes, the camel-parts were removed on purpose. See #154 for details.

As for the line length... is this not covered by the autoformatter?

**Comment by middagj** [comment]
No, apparently not. But fixed it.

**Comment by turing85** [comment]
Official release is on 2023-04-26. How about we build the `3.0.0` 1 day before, i.e. on 2023-04-25?

**Comment by zhfeng** [comment]
@turing85 Can we release two days before because also need to release `quarkus-pooled-jms` which depends on `quarkus-artems-jms` although it is just for testing.

**Comment by turing85** [comment]
So 2023-04-04 it is :slightly_smiling_face:

**Comment by turing85** [comment]
Ad discussed with @zhfeng [here](https://github.com/quarkiverse/quarkus-artemis/pull/201#issuecomment-1515942362), we decided to release on 2023-04-20.

**Comment by gsmet** [comment]
It's today so cool for me :).

Please ping me in the release PR, thanks!
